apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - sockshop-staging-gateway.sockshop-staging
  - mesh
  hosts:
  - carts.sockshop-staging.35.202.209.235.xip.io
  - carts
  - carts.sockshop-staging
  http:
  - route:
    - destination:
        host: carts-canary.sockshop-staging.svc.cluster.local
    - destination:
        host: carts-primary.sockshop-staging.svc.cluster.local
      weight: 100
